[package]
name = "checkito"
version = "0.1.0"
authors = ["Magicolo <magicololand@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "*"
num_cpus = "*"