[package]
name = "checkito"
version = "2.0.0"
authors = ["Magicolo <magicololand@gmail.com>"]
edition = "2021"
readme = "README.md"
documentation = "https://docs.rs/checkito/latest/checkito/"
description = "A safe, efficient and simple QuickCheck inspired library to generate shrinkable random data mainly oriented towards generative/property/exploratory testing."
license = "MIT"
repository = "https://github.com/Magicolo/checkito"
keywords = ["property", "testing", "quickcheck", "fuzz", "hypothesis"]
categories = ["development-tools::testing"]
build = "build.rs"
rust-version = "1.65.0"

[dependencies]
checkito_macro = { path = "checkito_macro" }
fastrand = "2.1.1"
regex-syntax = "0.8.5"
orn = "0.4.3"

[dev-dependencies]
regex = "1.11.0"
criterion = "0.5.1"
skeptic = "0.13.7"

[build-dependencies]
skeptic = "0.13.7"
