[package]
name = "checkito"
version = "1.3.10"
authors = ["Magicolo <magicololand@gmail.com>"]
edition = "2021"
readme = "README.md"
documentation = "https://docs.rs/checkito/latest/checkito/"
description = "A simple quickcheck inspired library to generate growable/shrinkable random data mainly oriented towards generative/property/exploratory testing."
license = "MIT"
repository = "https://github.com/Magicolo/checkito"
keywords = ["property", "testing", "quickcheck", "fuzz", "hypothesis"]
categories = ["development-tools::testing"]
build = "build.rs"
rust-version = "1.65.0"

[dependencies]
fastrand = "2.0.1"
regex-syntax = "0.8.2"

[dev-dependencies]
regex = "1.10.2"
criterion = "0.5.1"
skeptic = "0.13.7"

[build-dependencies]
skeptic = "0.13.7"
