[package]
name = "checkito"
version = "1.3.5"
authors = ["Magicolo <magicololand@gmail.com>"]
edition = "2021"
readme = "README.md"
documentation = "https://docs.rs/checkito/latest/checkito/"
description = "A simple and efficient 'quickcheck' inspired library to generate random data mainly oriented towards generative/property/exploratory testing."
license = "MIT"
repository = "https://github.com/Magicolo/checkito"
keywords = ["property", "testing", "quickcheck", "fuzz", "hypothesis"]
categories = ["development-tools::testing"]
build = "build.rs"

[dependencies]
fastrand = "1.9.0"
regex-syntax = "0.7.1"

[dev-dependencies]
regex = "*"
skeptic = "*"

[build-dependencies]
skeptic = "*"