[package]
name = "checkito"
version = "1.3.7"
authors = ["Magicolo <magicololand@gmail.com>"]
edition = "2021"
readme = "README.md"
documentation = "https://docs.rs/checkito/latest/checkito/"
description = "A simple quickcheck inspired library to generate growable/shrinkable random data mainly oriented towards generative/property/exploratory testing."
license = "MIT"
repository = "https://github.com/Magicolo/checkito"
keywords = ["property", "testing", "quickcheck", "fuzz", "hypothesis"]
categories = ["development-tools::testing"]
build = "build.rs"
rust-version = "1.63"

[dependencies]
fastrand = "2.0"
regex-syntax = "0.7"

[dev-dependencies]
regex = "1.9"
criterion = "0.5"
skeptic = "0.12"

[build-dependencies]
# Keep skeptic to version 0.12 until the dependency bug with 'cargo-metadata' is fixed...
skeptic = "0.12"
