[package]
name = "checkito"
version = "1.3.6"
authors = ["Magicolo <magicololand@gmail.com>"]
edition = "2021"
readme = "README.md"
documentation = "https://docs.rs/checkito/latest/checkito/"
description = "A simple quickcheck inspired library to generate growable/shrinkable random data mainly oriented towards generative/property/exploratory testing."
license = "MIT"
repository = "https://github.com/Magicolo/checkito"
keywords = ["property", "testing", "quickcheck", "fuzz", "hypothesis"]
categories = ["development-tools::testing"]
build = "build.rs"

[dependencies]
fastrand = "1.9"
regex-syntax = "0.7"

[dev-dependencies]
regex = "1.8"
criterion = "0.4"
skeptic = "0.13"

[build-dependencies]
skeptic = "0.13"
