[package]
name = "checkito"
version = "2.1.0"
authors = ["Magicolo <magicololand@gmail.com>"]
edition = "2021"
readme = "README.md"
documentation = "https://docs.rs/checkito/latest/checkito/"
description = "A safe, efficient and simple QuickCheck-inspired library to generate shrinkable random data mainly oriented towards generative/property/exploratory testing."
license = "MIT"
repository = "https://github.com/Magicolo/checkito"
keywords = ["property", "testing", "quickcheck", "fuzz", "hypothesis"]
categories = ["development-tools::testing"]
rust-version = "1.65.0"

[badges]
github = { repository = "Magicolo/checkito", workflow = "test" }

[features]
default = ["check", "regex"]
check = ["checkito_macro/check"]
regex = ["regex-syntax/unicode", "checkito_macro/regex"]

[dependencies]
orn = { version = "0.4.3" }
fastrand = { version = "2.1.1" }
checkito_macro = { version = "0.3.0", default-features = false, optional = true }
regex-syntax = { version = "0.8.5", default-features = false, optional = true }

[dev-dependencies]
regex = "1.11.0"
