[package]
name = "checkito"
version = "2.0.0"
authors = ["Magicolo <magicololand@gmail.com>"]
edition = "2021"
readme = "README.md"
documentation = "https://docs.rs/checkito/latest/checkito/"
description = "A safe, efficient and simple [QuickCheck](https://hackage.haskell.org/package/QuickCheck) inspired library to generate shrinkable random data mainly oriented towards generative/property/exploratory testing."
license = "MIT"
repository = "https://github.com/Magicolo/checkito"
keywords = ["property", "testing", "quickcheck", "fuzz", "hypothesis"]
categories = ["development-tools::testing"]
rust-version = "1.65.0"

[badges]
github = { repository = "Magicolo/checkito", workflow = "test" }

[dependencies]
checkito_macro = "0.2.2"
fastrand = "2.1.1"
regex-syntax = "0.8.5"
orn = "0.4.3"

[dev-dependencies]
regex = "1.11.0"
