[package]
name = "checkito"
version = "0.1.0"
authors = ["Magicolo <magicololand@gmail.com>"]
edition = "2021"
description = "A simple and efficient 'quickcheck' inspired library to generate random data mainly oriented towards generative/property/exploratory testing."
license = "MIT"
repository = "https://github.com/Magicolo/checkito"
keywords = ["test", "generative", "exploratory", "property", "random", "quickcheck", "check"]

[dependencies]
fastrand = "1.9.0"