[package]
name = "checkito_macro"
version = "0.2.4"
authors = ["Magicolo <magicololand@gmail.com>"]
edition = "2021"
documentation = "https://docs.rs/checkito_macro/latest/checkito_macro/"
description = "A set of macros to accompany the `checkito` crate."
license = "MIT"
repository = "https://github.com/Magicolo/checkito/checkito_macro"
keywords = ["property", "testing", "quickcheck", "fuzz", "hypothesis"]
categories = ["development-tools::testing"]
rust-version = "1.65.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.79", features = ["full"] }
quote = "1.0.37"
regex-syntax = "0.8.5"
