[package]
name = "checkito_macro"
version = "0.1.0"
authors = ["Magicolo <magicololand@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.48"
quote = "1.0.35"
regex-syntax = "0.8.2"