name: test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: rust:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: cargo install cargo-hack
    - name: Run Main
      run: cargo hack build --release --lib --bins --benches --tests --verbose --feature-powerset
    - name: Run Examples
      run: cargo hack build --release --examples --verbose
    - name: Run Macro
      working-directory: checkito_macro
      run: cargo hack build --release --all-targets --verbose --feature-powerset
  test:
    runs-on: ubuntu-latest
    container: 
      image: rust:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: cargo install cargo-hack
    - name: Run Main
      run: cargo hack test --release --lib --bins --benches --tests --verbose --feature-powerset
    - name: Run Examples
      run: cargo hack test --release --examples --verbose
    - name: Run Documentation
      run: cargo hack test --release --doc --verbose --feature-powerset
    - name: Run Macro
      working-directory: checkito_macro
      run: cargo hack test --release --all-targets --verbose --feature-powerset
  semver:
    runs-on: ubuntu-latest
    container: 
      image: rust:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: apt update && apt install cmake --yes && cargo install cargo-semver-checks
    - name: Run Main
      run: cargo semver-checks --verbose
      continue-on-error: true
  clippy:
    runs-on: ubuntu-latest
    container: 
      image: rust:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: rustup component add clippy && cargo install cargo-hack
    - name: Run Main
      run: cargo hack clippy --release --lib --bins --benches --tests --verbose --feature-powerset -- --deny warnings
    - name: Run Examples
      run: cargo hack clippy --release --examples --verbose -- --deny warnings
    - name: Run Macro
      working-directory: checkito_macro
      run: cargo hack clippy --release --all-targets --verbose --feature-powerset -- --deny warnings
  audit:
    runs-on: ubuntu-latest
    container: 
      image: rust:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: cargo install cargo-audit
    - name: Run Main
      run: cargo audit
    - name: Run Macro
      working-directory: checkito_macro
      run: cargo audit