name: test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: rust:latest
    steps:
    - uses: actions/checkout@v4
    - name: Run
      run: cargo build --release --verbose
  test:
    runs-on: ubuntu-latest
    container: 
      image: rust:latest
    steps:
    - uses: actions/checkout@v4
    - name: Run
      run: cargo test --release --verbose
  clippy:
    runs-on: ubuntu-latest
    container: 
      image: rust:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: rustup component add clippy
    - name: Run
      run: cargo clippy --release --verbose -- -D warnings
  audit:
    runs-on: ubuntu-latest
    container: 
      image: rust:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: cargo install cargo-audit
    - name: Run
      run: cargo audit
  # publish:
  #   runs-on: ubuntu-latest
  #   needs: [build, test]
  #   container:
  #     image: rust:latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Log In
  #     run: cargo login --verbose ${{ secrets.CRATES_IO_API_TOKEN }}
  #   - name: Publish
  #     run: cargo publish