name: test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/magicolo/rust
        strategy:
            matrix:
                command:
                    - cargo hack nextest run --release --lib --bins --benches --tests --verbose --feature-powerset
                    - cargo hack nextest run --release --lib --bins --benches --tests --verbose --feature-powerset --rust-version
                    - cargo hack test --release --doc --verbose --all-features
                    - cargo hack test --release --examples --verbose --all-features
        steps:
            - uses: actions/checkout@v6
            - run: ${{ matrix.command }}
    clippy:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/magicolo/rust
        steps:
            - uses: actions/checkout@v6
            - run: cargo hack clippy --release --all-targets --verbose --all-features -- --deny warnings --allow clippy::test-attr-in-doctest
    doc:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/magicolo/rust
        steps:
            - uses: actions/checkout@v6
            - run: cargo hack doc --no-deps --release --verbose --all-features
    semver:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/magicolo/rust
        steps:
            - uses: actions/checkout@v6
            - run: cargo semver-checks --verbose
    msrv:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/magicolo/rust
        steps:
            - uses: actions/checkout@v6
            - run: cargo msrv verify --manifest-path checkito/Cargo.toml
            - run: cargo msrv verify --manifest-path checkito_macro/Cargo.toml
    audit:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/magicolo/rust
        steps:
            - uses: actions/checkout@v6
            - run: cargo audit --deny warnings
    coverage:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/magicolo/rust
        steps:
            - uses: actions/checkout@v6
            - run: cargo llvm-cov --fail-under-regions 75 --all-features --all-targets --release --verbose
