name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: |
        rustup toolchain install stable --component miri
        rustup override set stable
        cargo miri setup
    - name: Build Debug
      run: cargo clean && cargo build --verbose
    - name: Build Release
      run: cargo clean && cargo build --release --verbose
    - name: Run Debug tests
      run: cargo clean && cargo test --verbose
    - name: Run Release tests
      run: cargo clean && cargo test --release --verbose
    - name: Run Miri tests
      run: cargo clean && cargo miri test --verbose
