name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test-debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: rustup install stable && rustup default stable
    - name: Build
      run: cargo clean && cargo build --verbose
    - name: Test
      run: cargo clean && cargo test --verbose
  test-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: rustup install stable && rustup default stable
    - name: Build
      run: cargo clean && cargo build --release --verbose
    - name: Test
      run: cargo clean && cargo test --release --verbose
  test-miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: rustup install nightly && rustup default nightly && rustup component add miri
    - name: Test
      run: cargo clean && cargo miri test --verbose