name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: rustup install stable
    - name: Build Debug
      run: cargo clean && cargo build --verbose
    - name: Build Release
      run: cargo clean && cargo build --release --verbose
    - name: Run Debug tests
      run: cargo clean && cargo test --verbose
    - name: Run Release tests
      run: cargo clean && cargo test --release --verbose