name: test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: rust:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: cargo install cargo-hack
    - name: Run
      run: cargo hack build --release --all-targets --verbose --feature-powerset
  test:
    runs-on: ubuntu-latest
    container: 
      image: rust:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: cargo install cargo-hack
    - name: Run Tests
      run: cargo hack test --release --all-targets --verbose --feature-powerset
    - name: Run Documentation
      run: cargo hack test --release --doc --verbose --feature-powerset
  semver:
    runs-on: ubuntu-latest
    container: 
      image: rust:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: apt update && apt install cmake --yes && cargo install cargo-semver-checks
    - name: Run
      run: cargo semver-checks --verbose
  clippy:
    runs-on: ubuntu-latest
    container: 
      image: rust:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: rustup component add clippy && cargo install cargo-hack
    - name: Run
      run: cargo hack clippy --release --verbose --feature-powerset -- -D warnings
  audit:
    runs-on: ubuntu-latest
    container: 
      image: rust:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: cargo install cargo-audit
    - name: Run
      run: cargo audit